### ISSUE TITLE
Unable to create Yarn cluster due to permissions

### ISSUE THREAD

**Issue by bschreck** [dask/dask-gateway#128]
It seems skein tries to deploy a YARN cluster with my username (benschreck), rather than dask or hadoop? Getting the following error:
```
[E 2019-09-25 20:34:46.415 DaskGateway] Error while starting cluster 19f76a979aa3457bab7f1d39a0bcd20a
    Traceback (most recent call last):
      File "/mnt/var/dask-gateway/miniconda/lib/python3.6/site-packages/dask_gateway_server/app.py", line 722, in start_cluster
        timeout=cluster.manager.cluster_start_timeout,
      File "/mnt/var/dask-gateway/miniconda/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
        return fut.result()
      File "/mnt/var/dask-gateway/miniconda/lib/python3.6/site-packages/dask_gateway_server/app.py", line 707, in _start_cluster
        async for state in cluster.manager.start_cluster():
      File "/mnt/var/dask-gateway/miniconda/lib/python3.6/site-packages/dask_gateway_server/managers/yarn.py", line 293, in start_cluster
        app_id = await loop.run_in_executor(None, skein_client.submit, spec)
      File "/mnt/var/dask-gateway/miniconda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/mnt/var/dask-gateway/miniconda/lib/python3.6/site-packages/skein/core.py", line 509, in submit
        resp = self._call('submit', spec.to_protobuf())
      File "/mnt/var/dask-gateway/miniconda/lib/python3.6/site-packages/skein/core.py", line 289, in _call
        raise self._server_error(exc.details())
    skein.exceptions.DriverError: Failed to submit application, exception:
    Permission denied: user=benschreck, access=WRITE, inode="/user":hdfs:hadoop:drwxr-xr-x
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:319)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:219)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:189)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1663)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1647)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1606)
        at org.apache.hadoop.hdfs.server.namenode.FSDirMkdirOp.mkdirs(FSDirMkdirOp.java:60)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.mkdirs(FSNamesystem.java:3049)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.mkdirs(NameNodeRpcServer.java:1079)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.mkdirs(ClientNamenodeProtocolServerSideTranslatorPB.java:652)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:447)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:989)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:850)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:793)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2489)

```

My Gateway is running using the following params (some are environment variables I set):

```
c.DaskGateway.cluster_manager_class = "dask_gateway_server.managers.yarn.YarnClusterManager"
c.DaskGateway.authenticator_class = "dask_gateway_server.auth.DummyAuthenticator"

c.DaskGateway.public_url = "http://:$DASK_GATEWAY_APPLICATION_PORT"
c.DaskGateway.gateway_url = "tls://:$DASK_SCHEDULER_PORT"


# The resource limits for a worker
c.YarnClusterManager.worker_memory = '$WORKER_MEM G'
c.YarnClusterManager.worker_cores = $WORKER_VCORES
c.YarnClusterManager.scheduler_memory = '$SCHEDULER_MEM G'
c.YarnClusterManager.scheduler_cores = $SCHEDULER_VCORES
c.YarnClusterManager.localize_files = {
    'environment': {
        'source': '$HDFS_PACKED_ENV',
        'visibility': 'public'
    }
}
c.YarnClusterManager.environment = {'HADOOP_HOME': '/usr'}
c.YarnClusterManager.scheduler_setup = 'source default/bin/activate'
c.YarnClusterManager.worker_setup = 'source default/bin/activate'
```

**Comment by jcrist** [comment]
Apologies for the delayed response here, I've been out for the last week (conference, then vacation). Dask-Gateway is written to start clusters for multiple users - as such it needs security permissions for whatever the backing system is. Currently this is non-optional, as we don't want to encourage insecure behavior. See https://gateway.dask.org/install-hadoop.html for full hadoop installation instructions. In particular, you need proxy-user permissions for the account running dask-gateway.

If you can provide a good argument for why we should make proxy-user permissions optional, I may be willing to make this support optional. In this case, all clusters would be run as the same user account, regardless of who's logged in.

**Comment by bschreck** [comment]
No problem.

I'm pretty sure I have proxy-user permissions for both the `dask` and `hadoop` users. Currently I'm running the dask gateway as the `hadoop` user. Is there a need for it to specifically be running as the `dask` user? And does that error look like the error I would get if I did not actually have proxy user permissions? In particular, I did specify `hadoop.proxyuser.{user}.hosts` and `hadoop.proxyuser.{user}.groups` for both `hadoop` and `dask`

**Comment by jcrist** [comment]
The username that `dask-gateway-server` runs as doesn't matter, what matters is that the account has proxy-user permissions for all users submitting clusters. Since you're running `dask-gateway-server` as the `hadoop` user and the server is successfully proxying you as `benschreck`, then this is working fine.

The failure here appears to be that user `benschreck` doesn't have permission to write to the `/user` directory on HDFS. Do you have a home directory on HDFS? We rely on the Java libraries to infer your home directory, perhaps if it's missing it falls back to `/user` which you don't have permissions for. On application submission a small bundle is uploaded to HDFS and stored in `~/.skein`, this upload is what's failing.

**Comment by bschreck** [comment]
Got it, that makes sense. I'll dig deeper on hdfs perms

**Comment by jcrist** [comment]
Closing as stale. Feel free to reopen if the problem persists.
