### ISSUE TITLE
KeyError when starting dask-gateway-server

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-gateway#131]
Probably user error, but I see this in my logs with dask-gateway 0.4.1 when deploying on kubernetes

```
 $ kubectl -n dask-gateway log gateway-dask-gateway-6b77565b47-jhcss        366ms
[I 2019-10-02 13:02:44.454 DaskGateway] Starting dask-gateway-server - version 0.4.1
[E 2019-10-02 13:02:44.455 DaskGateway] Exception while loading config file /etc/dask-gateway/dask_gateway_config.py
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/opt/conda/lib/python3.7/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/opt/conda/lib/python3.7/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/opt/conda/lib/python3.7/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/etc/dask-gateway/dask_gateway_config.py", line 106, in <module>
        api_url = "http://{HUB_SERVICE_HOST}:{HUB_SERVICE_PORT}/hub/api".format(**os.environ)
    KeyError: 'HUB_SERVICE_HOST'
[I 2019-10-02 13:02:44.457 DaskGateway] Cluster manager: 'dask_gateway_server.managers.local.UnsafeLocalClusterManager'
[I 2019-10-02 13:02:44.457 DaskGateway] Authenticator: 'dask_gateway_server.auth.DummyAuthenticator'
[I 2019-10-02 13:02:44.472 DaskGateway] Starting the Dask gateway scheduler proxy...
[I 2019-10-02 13:02:44.476 DaskGateway] Dask gateway scheduler proxy started at 'tls://gateway-dask-gateway-6b77565b47-jhcss:8786', api at 'http://127.0.0.1:35285'
```

Here's my helm config

```yaml
gateway:
  proxyToken: "<>"

  auth:
    type: jupyterhub
    jupyterhub:
      apiToken: "<>"

  clusterManager:
    image:
      name: "gcr.io/dask-demo-182016/anaconda-gartner"
      tag: latest
    scheduler:
      extraPodConfig:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: DoesNotExist
    worker:
      extraPodConfig:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Equal
        tolerations:
          Toleration:
            - key: "preemptible"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
```

**Comment by TomAugspurger** [comment]
Not sure if it matters, I was just using jhub's dummy auth

```yaml
proxy:
  secretToken: <>

singleuser:
  image:
    name: "gcr.io/dask-demo-182016/anaconda-gartner"
    tag: latest

hub:
  services:
    dask-gateway:
      apiToken: "<>"

auth:
  type: dummy
  dummy:
    password: '<>'
  whitelist:
    users:
      - <>
```

**Comment by jcrist** [comment]
I assume you're running the gateway under a different cluster/different namespace than jupyterhub? In this case you'll need to manually specify the apiurl in the gateway config:

```
  auth:
    type: jupyterhub
    jupyterhub:
      apiToken: "<>"
      apiUrl: <jupyterhub-api-url>  # this usually ends with /hub/api
```

When run in the same cluster & namespace, dask-gateway can infer this from the corresponding kubernetes service.
