### ISSUE TITLE
dask-gateway-scheduler pod got OOMKilled

### ISSUE THREAD

**Issue by ericdill** [dask/dask-gateway#139]
Not 100% sure why this happened or how to gather more information, but I happened to be watching my k8s pods (`watch kubectl get po -n dask-gateway`) and saw that my scheduler pod got OOMKilled. The gateway log has the following line;

```
[W 2019-10-07 09:54:22.473 DaskGateway] Cluster b51b5f2b687d4b5eb9c020de892ebf07 stopped unexpectedly: Container stopped with exit code 137
```

And in my notebook i got a StreamClosedError
```
---------------------------------------------------------------------------
StreamClosedError                         Traceback (most recent call last)
~/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/comm/tcp.py in read(self, deserializers)
    183         try:
--> 184             n_frames = await stream.read_bytes(8)
    185             n_frames = struct.unpack("Q", n_frames)[0]

StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

CommClosedError                           Traceback (most recent call last)
<ipython-input-210-e6a074d7e0bd> in <module>
----> 1 ret = df.compute()

~/anaconda/envs/airflow/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    173         dask.base.compute
    174         """
--> 175         (result,) = compute(self, traverse=False, **kwargs)
    176         return result
    177 

~/anaconda/envs/airflow/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    444     keys = [x.__dask_keys__() for x in collections]
    445     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 446     results = schedule(dsk, keys, **kwargs)
    447     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    448 

~/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2518                     should_rejoin = False
   2519             try:
-> 2520                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2521             finally:
   2522                 for f in futures.values():

~/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1818                 direct=direct,
   1819                 local_worker=local_worker,
-> 1820                 asynchronous=asynchronous,
   1821             )
   1822 

~/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    752         else:
    753             return sync(
--> 754                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    755             )
    756 

~/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    335     if error[0]:
    336         typ, exc, tb = error[0]
--> 337         raise exc.with_traceback(tb)
    338     else:
    339         return result[0]

~/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/utils.py in f()
    319             if callback_timeout is not None:
    320                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 321             result[0] = yield future
    322         except Exception as exc:
    323             error[0] = sys.exc_info()

~/anaconda/envs/airflow/lib/python3.6/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1703                 else:
   1704                     self._gather_future = future
-> 1705                 response = await future
   1706 
   1707             if response["status"] == "error":

~/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py in _gather_remote(self, direct, local_worker)
   1755 
   1756             else:  # ask scheduler to gather data for us
-> 1757                 response = await self.scheduler.gather(keys=keys)
   1758         finally:
   1759             self._gather_semaphore.release()

~/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/core.py in send_recv_from_rpc(**kwargs)
    736             name, comm.name = comm.name, "ConnectionPool." + key
    737             try:
--> 738                 result = await send_recv(comm=comm, op=key, **kwargs)
    739             finally:
    740                 self.pool.reuse(self.addr, comm)

~/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/core.py in send_recv(comm, reply, serializers, deserializers, **kwargs)
    529         await comm.write(msg, serializers=serializers, on_error="raise")
    530         if reply:
--> 531             response = await comm.read(deserializers=deserializers)
    532         else:
    533             response = None

~/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/comm/tcp.py in read(self, deserializers)
    202             self.stream = None
    203             if not shutting_down():
--> 204                 convert_stream_closed_error(self, e)
    205         else:
    206             try:

~/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/comm/tcp.py in convert_stream_closed_error(obj, exc)
    130         raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
    131     else:
--> 132         raise CommClosedError("in %s: %s" % (obj, exc))
    133 
    134 

CommClosedError: in <closed TLS>: Stream is closed
distributed.client - ERROR - Failed to reconnect to scheduler after 10.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 10.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 10.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 10.00 seconds, closing client
distributed.utils - ERROR - 
Traceback (most recent call last):
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/utils.py", line 666, in log_errors
    yield
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py", line 1276, in _close
    await gen.with_timeout(timedelta(seconds=2), list(coroutines))
concurrent.futures._base.CancelledError
distributed.utils - ERROR - 
Traceback (most recent call last):
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/utils.py", line 666, in log_errors
    yield
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py", line 1005, in _reconnect
    await self._close()
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py", line 1276, in _close
    await gen.with_timeout(timedelta(seconds=2), list(coroutines))
concurrent.futures._base.CancelledError
distributed.utils - ERROR - 
Traceback (most recent call last):
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/utils.py", line 666, in log_errors
    yield
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py", line 1276, in _close
    await gen.with_timeout(timedelta(seconds=2), list(coroutines))
concurrent.futures._base.CancelledError
distributed.utils - ERROR - 
Traceback (most recent call last):
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/utils.py", line 666, in log_errors
    yield
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py", line 1005, in _reconnect
    await self._close()
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py", line 1276, in _close
    await gen.with_timeout(timedelta(seconds=2), list(coroutines))
concurrent.futures._base.CancelledError
distributed.utils - ERROR - 
Traceback (most recent call last):
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/utils.py", line 666, in log_errors
    yield
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py", line 1276, in _close
    await gen.with_timeout(timedelta(seconds=2), list(coroutines))
concurrent.futures._base.CancelledError
distributed.utils - ERROR - 
Traceback (most recent call last):
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/utils.py", line 666, in log_errors
    yield
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py", line 1005, in _reconnect
    await self._close()
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py", line 1276, in _close
    await gen.with_timeout(timedelta(seconds=2), list(coroutines))
concurrent.futures._base.CancelledError
distributed.utils - ERROR - 
Traceback (most recent call last):
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/utils.py", line 666, in log_errors
    yield
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py", line 1276, in _close
    await gen.with_timeout(timedelta(seconds=2), list(coroutines))
concurrent.futures._base.CancelledError
distributed.utils - ERROR - 
Traceback (most recent call last):
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/utils.py", line 666, in log_errors
    yield
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py", line 1005, in _reconnect
    await self._close()
  File "/opt/continuum/anaconda/envs/airflow/lib/python3.6/site-packages/distributed/client.py", line 1276, in _close
    await gen.with_timeout(timedelta(seconds=2), list(coroutines))
concurrent.futures._base.CancelledError
```

This is the code that was being executed (well this is some of the relevant code that had been executed prior)
```
import dask.dataframe as dd
small = dd.read_parquet('gs://edill-data/flights/parquet/2006')#, gather_statistics=False, validate_schema=False)
small = client.persist(small)
df['ComputedAirTime'] = df['ArrTime'] - df['DepTime']
df['AirTimeDelta'] = df['ComputedAirTime'] - df['AirTime']
```
And here's the cell that I ran when the scheduler got OOMKilled
```
ret = df.compute()
```

Anything else I can provide to figure out if there's a bug on the dask-gateway side?

**Comment by ericdill** [comment]
Ohhh I see what's happening. `df` in this case was substantially larger than anticipated (100ish million rows) so when I try and pull that back as a pandas dataframe the scheduler memory (I'm guessing) exploded and k8s killed it.

**Comment by jcrist** [comment]
Ah, yeah, currently the results are pulled back to the scheduler before being forwarded to the client. There might be a way to change the protocol so results are streamed back to the client through the scheduler, reducing maximum memory usage on the scheduler. However, currently you'll need to have a scheduler memory limit > your maximum result returned to the client. The default is 2 GiB, which seems to be sufficient for most problems (it's the default on dask-yarn as well).

**Comment by jcrist** [comment]
Closing for now, as this issue is external to dask-gateway.
