### ISSUE TITLE
Yarn application starts but gateway fails to connect

### ISSUE THREAD

**Issue by bschreck** [dask/dask-gateway#152]
I'm able to create a yarn application remotely by doing `gateway.new_cluster()`, but it seems like the gateway is not able to connect to it. I see the Yarn application runnign with correctly allocated memory in the Hadoop UI, but receive the following error from gateway:

```
[I 2019-10-08 22:01:22.635 DaskGateway] 201 POST /api/clusters/ (127.0.0.1) 176.36ms
[I 2019-10-08 22:01:22.635 DaskGateway] Starting cluster 9701da16751643f8af21e1897023a2a1 for user hadoop...
19/10/08 22:01:23 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/10/08 22:01:24 INFO client.RMProxy: Connecting to ResourceManager at ip-10-200-39-182.ec2.internal/10.200.39.182:8032
19/10/08 22:01:25 INFO skein.Driver: Driver started, listening on 44959
19/10/08 22:01:25 INFO client.RMProxy: Connecting to ResourceManager at ip-10-200-39-182.ec2.internal/10.200.39.182:8032
19/10/08 22:01:25 INFO skein.Driver: Uploading application resources to hdfs://ip-10-200-39-182.ec2.internal:8020/user/hadoop/.skein/application_1569444844120_0006
19/10/08 22:01:26 INFO skein.Driver: Submitting application...
19/10/08 22:01:26 INFO impl.YarnClientImpl: Submitted application application_1569444844120_0006
[D 2019-10-08 22:01:26.434 DaskGateway] State update for cluster 9701da16751643f8af21e1897023a2a1
[I 2019-10-08 22:01:26.438 DaskGateway] Cluster 9701da16751643f8af21e1897023a2a1 has started, waiting for connection
[I 2019-10-08 22:01:42.655 DaskGateway] 200 GET /api/clusters/9701da16751643f8af21e1897023a2a1?wait (127.0.0.1) 19930.13ms
[I 2019-10-08 22:02:03.164 DaskGateway] 200 GET /api/clusters/9701da16751643f8af21e1897023a2a1?wait (127.0.0.1) 20006.16ms
[I 2019-10-08 22:02:23.685 DaskGateway] 200 GET /api/clusters/9701da16751643f8af21e1897023a2a1?wait (127.0.0.1) 20019.21ms
[W 2019-10-08 22:02:26.442 DaskGateway] Cluster 9701da16751643f8af21e1897023a2a1 failed to connect after 60.0 seconds
[I 2019-10-08 22:02:26.442 DaskGateway] Stopping cluster 9701da16751643f8af21e1897023a2a1...
[D 2019-10-08 22:02:26.443 DaskGateway] Removing route '/gateway/clusters/9701da16751643f8af21e1897023a2a1'
[I 2019-10-08 22:02:26.444 DaskGateway] 200 GET /api/clusters/9701da16751643f8af21e1897023a2a1?wait (127.0.0.1) 2255.80ms
[D 2019-10-08 22:02:26.446 DaskGateway] Removing route '/9701da16751643f8af21e1897023a2a1'
19/10/08 22:02:26 INFO impl.YarnClientImpl: Killed application application_1569444844120_0006
[I 2019-10-08 22:02:26.464 DaskGateway] Stopped cluster 9701da16751643f8af21e1897023a2a1
[I 2019-10-08 22:02:26.948 DaskGateway] 200 GET /api/clusters/9701da16751643f8af21e1897023a2a1?wait (127.0.0.1) 0.79ms
[I 2019-10-08 22:02:26.951 DaskGateway] 204 DELETE /api/clusters/9701da16751643f8af21e1897023a2a1 (127.0.0.1) 0.51ms
```

**Comment by bschreck** [comment]
I found the logs from the container:

```
distributed.scheduler - INFO - Clear task state
distributed.dashboard.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: pip install jupyter-server-proxy
distributed.scheduler - INFO -   Scheduler at:  tls://10.200.37.86:46121
distributed.scheduler - INFO -     gateway at:                    :45499
distributed.scheduler - INFO -   dashboard at:                    :34475
Failed to send addresses to gateway
Traceback (most recent call last):
  File "/mnt1/yarn/usercache/benschreck/appcache/application_1569444844120_0011/container_1569444844120_0011_01_000001/environment/lib/python3.6/site-packages/dask_gateway/dask_cli.py", line 331, in start_scheduler
    await gateway.send_addresses(scheduler.address, dashboard_address, api_address)
  File "/mnt1/yarn/usercache/benschreck/appcache/application_1569444844120_0011/container_1569444844120_0011_01_000001/environment/lib/python3.6/site-packages/dask_gateway/dask_cli.py", line 197, in send_addresses
    await client.fetch(req)
  File "/mnt1/yarn/usercache/benschreck/appcache/application_1569444844120_0011/container_1569444844120_0011_01_000001/environment/lib/python3.6/site-packages/tornado/simple_httpclient.py", line 336, in run
    source_ip=source_ip,
  File "/mnt1/yarn/usercache/benschreck/appcache/application_1569444844120_0011/container_1569444844120_0011_01_000001/environment/lib/python3.6/site-packages/tornado/tcpclient.py", line 270, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/mnt1/yarn/usercache/benschreck/appcache/application_1569444844120_0011/container_1569444844120_0011_01_000001/environment/lib/python3.6/site-packages/tornado/netutil.py", line 396, in resolve
    None, _resolve_addr, host, port, family
  File "/mnt1/yarn/usercache/benschreck/appcache/application_1569444844120_0011/container_1569444844120_0011_01_000001/environment/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt1/yarn/usercache/benschreck/appcache/application_1569444844120_0011/container_1569444844120_0011_01_000001/environment/lib/python3.6/site-packages/tornado/netutil.py", line 379, in _resolve_addr
    addrinfo = socket.getaddrinfo(host, port, family, socket.SOCK_STREAM)
  File "/mnt1/yarn/usercache/benschreck/appcache/application_1569444844120_0011/container_1569444844120_0011_01_000001/environment/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by bschreck** [comment]
I figured this out. Had to downgrade Tornado to 5.1.1
