### ISSUE TITLE
scale(0) results in server error

### ISSUE THREAD

**Issue by martindurant** [dask/dask-gateway#157]
Traceback on gateway server as follows:
```
[E 2019-10-30 20:08:50.636 DaskGateway] Uncaught exception PUT /api/clusters/1b4050f2d8964f26848fe8e120d85c77/workers (192.168.37.29)
    HTTPServerRequest(protocol='http', host='10.100.222.73:8001', method='PUT', uri='/api/clusters/1b4050f2d8964f26848fe8e120d85c77/workers', version='HTTP/1.1', remote_ip='192.168.37.29')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/handlers.py", line 25, in inner
        return await method(self, *args, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/handlers.py", line 280, in put
        n, msg = await self.gateway.scale(cluster, total)
      File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/app.py", line 938, in scale
        actual_delta = -await self.scale_down(cluster, -delta)
      File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/app.py", line 1144, in scale_down
        resp = await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 500: Internal Server Error
[E 2019-10-30 20:08:50.637 DaskGateway] 500 PUT /api/clusters/1b4050f2d8964f26848fe8e120d85c77/workers (192.168.37.29) 7.12ms
```

the scheduler pod says
```
tornado.application - ERROR - Uncaught exception POST /api/scale_down (192.168.71.90)
HTTPServerRequest(protocol='http', host='192.168.77.125:46717', method='POST', uri='/api/scale_down', version='HTTP/1.1', remote_ip='192.168.71.90')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/opt/conda/lib/python3.7/site-packages/dask_gateway/dask_cli.py", line 61, in post
    result = await self.gateway_service.scale_down(remove_count)
  File "/opt/conda/lib/python3.7/site-packages/dask_gateway/dask_cli.py", line 112, in scale_down
    workers_closed = [v["name"] for v in closed.values()]
AttributeError: 'list' object has no attribute 'values'
```

**Comment by jcrist** [comment]
Hmmm, that's odd. I don't think this has ever worked properly, I'm curious why our tests haven't caught this. The docstring for `retire_workers` (says it returns a dict) doesn't match it's implementation (returns a list). I think just dropping the `.values()` from this should work. We should also figure out why the scale down tests pass even with this error.
