### ISSUE TITLE
invalid state tornado exception

### ISSUE THREAD

**Issue by chrisroat** [dask/dask-gateway#272]
I apologize that this is not self-contained, but it happens intermittently.  After doing a `dask.compute(tasks, scheduler=client)`, I typically see the traceback below.  It seems to only happen on certain workloads that are using [cloud-volume](https://github.com/seung-lab/cloud-volume).

It a recent case, it took about 5 minutes for the processing to show up in the scheduler's UI, and the exception occurred right at the moment the tasks all appeared there in the progress window.  As best I can tell, the computation then occurs correctly.  The client maintains connection and I can re-use it to submit more work.  On one occasion, the cluster shuts down and I have to start a new one.

Since this is coming from tornado, I note that the notebook I'm submitting from, and the containers running on the worker containers, are running with tornado=5.1.1.

**What happened**:
```
tornado.application - ERROR - Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/iostream.py", line 752, in wrapper
    return callback(*args)
  File "/opt/conda/lib/python3.7/site-packages/tornado/iostream.py", line 1407, in <lambda>
    ssl_stream._ssl_connect_callback = lambda: future.set_result(ssl_stream)
asyncio.base_futures.InvalidStateError: invalid state
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f10485c55f0>)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tornado/iostream.py", line 752, in wrapper
    return callback(*args)
  File "/opt/conda/lib/python3.7/site-packages/tornado/iostream.py", line 1407, in <lambda>
    ssl_stream._ssl_connect_callback = lambda: future.set_result(ssl_stream)
asyncio.base_futures.InvalidStateError: invalid state
tornado.application - ERROR - Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/iostream.py", line 752, in wrapper
    return callback(*args)
  File "/opt/conda/lib/python3.7/site-packages/tornado/iostream.py", line 1407, in <lambda>
    ssl_stream._ssl_connect_callback = lambda: future.set_result(ssl_stream)
asyncio.base_futures.InvalidStateError: invalid state
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f1051afb0e0>)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tornado/iostream.py", line 752, in wrapper
    return callback(*args)
  File "/opt/conda/lib/python3.7/site-packages/tornado/iostream.py", line 1407, in <lambda>
    ssl_stream._ssl_connect_callback = lambda: future.set_result(ssl_stream)
asyncio.base_futures.InvalidStateError: invalid state
```

**Environment**:

- Dask version: 2.15.0 (dask), 2.15.2 (distributed), 0.7.1 (dask-gateway)
- Python version: 3.7.6
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): conda (dask, distributed), pip (dask-gateway)
- Tornado version 5.1.1

**Comment by jcrist** [comment]
Hmmm, that's pretty odd. I've never run into that before. Where does that exception occur (client? scheduler? worker?). Could you try with a newer version of tornado? 5.1.1 came out in 2018 and is a bit old. FWIW this code path doesn't have anything to do with dask-gateway, and could likely be reproduced with normal distributed using ssl.

**Comment by chrisroat** [comment]
If it's not dask-gateway, then I apologize for posting here.  I had developed on a local cluster previously, and hadn't seen it.  I will attempt to upgrade tornado (one of my other deps relies on tornado<6... sigh)

**Comment by jennakwon06** [comment]
Hello, I am getting this as well and I also have tornado 5.1.1. Did tornado 6 fix the issue?

**Comment by chrisroat** [comment]
I did move to tornado 6 eventually, and I don't have this error.  But I also have changed many other packages, as well (e.g., dask-gateway has had a release since I posted this).
