### ISSUE TITLE
`get_cluster` hangs on kubeclusterconfig environment option with "valueFrom": "secretKeyRef"

### ISSUE THREAD

**Issue by shaunc** [dask/dask-gateway#312]
**What happened**:

Using helm chart, if I specify option:
```
                Mapping
                  ("environment", 
                  label="Worker & scheduler environment vars"),
```
and pass it through in the handler:
```
return {
      ...
       "environment": options.environment,
      ...
}
```
And specify an option on the client, then create a cluster:
```
>>> options = gateway.cluster_options()
>>> options.environment = {'name': 'foo', 'valueFrom': {'secretKeyRef': {'name': 'foo', 'key': 'bar'}}}
>>> c = g.new_cluster(options)
```
Then cluster creation on client hangs, and I find in the controller logs:
```
[I 2020-09-08 02:43:21.075 KubeController] Reconciling cluster dask-gateway.75ff3ebd0dff4da6abd9cfd1f2c5e263
[I 2020-09-08 02:43:21.130 KubeController] Creating new credentials for cluster dask-gateway.75ff3ebd0dff4da6abd9cfd1f2c5e263
[I 2020-09-08 02:43:21.146 KubeController] Creating scheduler pod for cluster dask-gateway.75ff3ebd0dff4da6abd9cfd1f2c5e263
[W 2020-09-08 02:43:21.148 KubeController] Error while reconciling cluster dask-gateway.75ff3ebd0dff4da6abd9cfd1f2c5e263
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/dask_gateway_server/backends/kubernetes/controller.py", line 586, in reconciler_loop
    requeue = await self.reconcile_cluster(name)
  File "/opt/conda/lib/python3.8/site-packages/dask_gateway_server/backends/kubernetes/controller.py", line 607, in reconcile_cluster
    status_update, requeue = await self.handle_cluster(cluster)
  File "/opt/conda/lib/python3.8/site-packages/dask_gateway_server/backends/kubernetes/controller.py", line 643, in handle_cluster
    return await self.handle_pending_cluster(cluster)
  File "/opt/conda/lib/python3.8/site-packages/dask_gateway_server/backends/kubernetes/controller.py", line 661, in handle_pending_cluster
    sched_pod_name, sched_pod = await self.create_scheduler_pod_if_not_exists(
  File "/opt/conda/lib/python3.8/site-packages/dask_gateway_server/backends/kubernetes/controller.py", line 942, in create_scheduler_pod_if_not_exists
    pod = await self.core_client.create_namespaced_pod(namespace, pod)
  File "/opt/conda/lib/python3.8/site-packages/dask_gateway_server/backends/kubernetes/utils.py", line 59, in func
    return await method(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 162, in __call_api
    response_data = await self.request(
  File "/opt/conda/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 224, in POST
    return (await self.request("POST", url,
  File "/opt/conda/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 181, in request
    raise ApiException(http_resp=r)
kubernetes_asyncio.client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: <CIMultiDictProxy('Audit-Id': 'c8cb4160-74ba-4118-b1c0-c17f58368c3d', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 08 Sep 2020 02:43:21 GMT', 'Content-Length': '510')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod in version \"v1\" cannot be handled as a Pod: v1.Pod.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects \" or n, but found {, error found in #10 byte of ...|\"value\": {\"secretKey|..., bigger context ...| \"value\": \"foo\"}, {\"name\": \"valueFrom\", \"value\": {\"secretKeyRef\": {\"key\": \"bar\", \"name\": \"foo\"}}}, {|...","reason":"BadRequest","code":400}
```

**What you expected to happen**:

**Either**

1) In the best case, a cluster would be created in which workers had environment variable set from secret.
2) Or, at least, the error would be propagated to the client, or even better caught when option is set (in which case this report would be a feature request).

**Minimal Complete Verifiable Example**:

The above should suffice to reproduce.

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

**UPDATE**: with some additional threading through, the following works to add environment config
from a secret:
```
options.worker_extra_container_config = {'env': [{'name': 'foo', 'valueFrom': {'secretKeyRef': {'name': 'foo', 'key': 'bar'}}}]}
```
I guess then that `options.environment` is "syntactic sugar" in some sense -- so proper error is the most important part. Documenting that `options.environment` is not appropriate for referencing a secret key, but that `options.worker_extra_container_config` cam be used instead, would be quite helpful.

**Environment**:

Kubernetes 1.17 running in EKS, using 0.8.0 chart (ok -- with pull secrets modifications I submitted in PR, but that shouldn't affect this).

- Dask version: 2.21.0
- Python version: py3.8 (again -- as in PR)
- Operating System: debian buster slim (using Dask Gateway image as base)
- Install method (conda, pip, source): kubectl; client dask_gateway via pip

**Comment by shaunc** [comment]
Ach ... now that I think about it, trying to use `environment` to do this is silly -- it should take an array of dicts for that to work, and it doesn't. Doc update still would be nice, but closing as presumably not as relevant for users who get a proper night's sleep, unlike the author. :)
