### ISSUE TITLE
Simple AKS Deployment can't get_client

### ISSUE THREAD

**Issue by jabbera** [dask/dask-gateway#394]
Net new installation on AKS. When calling cluster.get_client() the following exception is thrown (Note: exception is thrown immediately as opposed to 10s):

OS error: Timed out during handshake while connecting to gateway://10.15.32.133:80/dask-gateway.7c570325fec840e69cdc5bd95c349bd4 after 10 s

Helm 0.9.0

values.yaml
```
gateway:
  auth:
    type: simple
    simple:
      password: test

traefik:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "load-balancers"
    spec:
      loadBalancerIP: 10.15.32.133
```
test code:
```
from dask_gateway import Gateway, BasicAuth
import time

auth = BasicAuth(username=None, password='test')

gateway = Gateway(
    address="http://10.15.32.133/",
    auth=auth
)

cluster = gateway.new_cluster()
cluster.adapt(minimum=1, maximum=10)


client = cluster.get_client()

gateway.close()
```

Full exception:
```
Traceback (most recent call last):
  File "/mnt/f/sandbox/dg/venv/lib/python3.8/site-packages/distributed/comm/core.py", line 318, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/mnt/f/sandbox/dg/venv/lib/python3.8/site-packages/distributed/comm/tcp.py", line 216, in read
    frames = unpack_frames(frames)
  File "/mnt/f/sandbox/dg/venv/lib/python3.8/site-packages/distributed/protocol/utils.py", line 70, in unpack_frames
    (n_frames,) = struct.unpack_from(fmt, b)
struct.error: unpack_from requires a buffer of at least 8 bytes for unpacking 8 bytes at offset 0 (actual buffer size is 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 15, in <module>
    client = cluster.get_client()
  File "/mnt/f/sandbox/dg/venv/lib/python3.8/site-packages/dask_gateway/client.py", line 1078, in get_client
    client = Client(
  File "/mnt/f/sandbox/dg/venv/lib/python3.8/site-packages/distributed/client.py", line 744, in __init__
    self.start(timeout=timeout)
  File "/mnt/f/sandbox/dg/venv/lib/python3.8/site-packages/distributed/client.py", line 960, in start
    sync(self.loop, self._start, **kwargs)
  File "/mnt/f/sandbox/dg/venv/lib/python3.8/site-packages/distributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "/mnt/f/sandbox/dg/venv/lib/python3.8/site-packages/distributed/utils.py", line 336, in f
    result[0] = yield future
  File "/mnt/f/sandbox/dg/venv/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/mnt/f/sandbox/dg/venv/lib/python3.8/site-packages/distributed/client.py", line 1050, in _start
    await self._ensure_connected(timeout=timeout)
  File "/mnt/f/sandbox/dg/venv/lib/python3.8/site-packages/distributed/client.py", line 1107, in _ensure_connected
    comm = await connect(
  File "/mnt/f/sandbox/dg/venv/lib/python3.8/site-packages/distributed/comm/core.py", line 323, in connect
    raise IOError(
OSError: Timed out during handshake while connecting to gateway://10.15.32.133:80/dask-gateway.a85816a4537145aea33e9553ed7eda11 after 10 s
```

Log files: api pod
```
[32m[I 2021-05-06 19:36:53.437 DaskGateway][0m Starting dask-gateway-server - version 0.9.0
[32m[I 2021-05-06 19:36:53.778 DaskGateway][0m Authenticator: 'dask_gateway_server.auth.SimpleAuthenticator'
[32m[I 2021-05-06 19:36:53.779 DaskGateway][0m Backend: 'dask_gateway_server.backends.kubernetes.backend.KubeBackend'
[32m[I 2021-05-06 19:36:53.828 DaskGateway][0m Dask-Gateway server started
[32m[I 2021-05-06 19:36:53.829 DaskGateway][0m - Private API server listening at http://:8000
[33m[W 2021-05-06 19:38:02.151 DaskGateway][0m 401 POST /api/v1/clusters/ 0.497ms
[32m[I 2021-05-06 19:38:02.174 DaskGateway][0m Creating cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4 for user jabbera
[32m[I 2021-05-06 19:38:02.208 DaskGateway][0m 201 POST /api/v1/clusters/ 35.222ms
[32m[I 2021-05-06 19:38:06.751 DaskGateway][0m 200 GET /api/v1/clusters/dask-gateway.7c570325fec840e69cdc5bd95c349bd4?wait 4521.742ms
[32m[I 2021-05-06 19:38:07.566 DaskGateway][0m 200 POST /api/v1/clusters/dask-gateway.7c570325fec840e69cdc5bd95c349bd4/adapt 11.221ms
[32m[I 2021-05-06 19:38:07.574 DaskGateway][0m Cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4 heartbeat [count: 1, n_active: 0, n_closing: 0, n_closed: 0]
[32m[I 2021-05-06 19:38:07.589 DaskGateway][0m 200 POST /api/v1/clusters/dask-gateway.7c570325fec840e69cdc5bd95c349bd4/heartbeat 15.502ms
```

traefik pod
```
time="2021-05-06T19:37:36Z" level=info msg="Configuration loaded from flags."
```

worker pod
```
distributed.nanny - INFO -         Start Nanny at: 'tls://10.15.40.184:39237'
distributed.worker - INFO -       Start worker at:   tls://10.15.40.184:44273
distributed.worker - INFO -          Listening to:   tls://10.15.40.184:44273
distributed.worker - INFO -          dashboard at:          10.15.40.184:8787
distributed.worker - INFO - Waiting to connect to: tls://dask-7c570325fec840e69cdc5bd95c349bd4.dask-gateway:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    2.15 GB
distributed.worker - INFO -       Local Directory: /home/dask/dask-worker-space/dask-worker-space/worker-c8m45zoz
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to: tls://dask-7c570325fec840e69cdc5bd95c349bd4.dask-gateway:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
```

secheduler pod
```
distributed.preloading - INFO - Import preload module: dask_gateway.scheduler_preload
distributed.scheduler - INFO - -----------------------------------------------
distributed.preloading - INFO - Import preload module: dask_gateway.scheduler_preload
distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:   tls://10.15.40.117:8786
distributed.scheduler - INFO -   dashboard at:                     :8787
distributed.comm.tcp - INFO - Connection closed before handshake completed
dask_gateway.scheduler_preload - INFO - Enabling adaptive scaling, minimum=1, maximum=10
dask_gateway.scheduler_preload - INFO - Requesting scale to 1 workers from 0
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.scheduler - INFO - Register worker <Worker 'tls://10.15.40.184:44273', name: dask-worker-7c570325fec840e69cdc5bd95c349bd4-bsg55, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tls://10.15.40.184:44273
distributed.core - INFO - Starting established connection
```

controller pod
```
[32m[I 2021-05-06 19:37:18.973 KubeController][0m Starting dask-gateway-kube-controller - version 0.9.0
[32m[I 2021-05-06 19:37:19.036 KubeController][0m Reconciling cluster dask-gateway.6e83a697b0414c2bb13907357678c19d
[32m[I 2021-05-06 19:37:19.036 KubeController][0m Finished reconciling cluster dask-gateway.6e83a697b0414c2bb13907357678c19d
[32m[I 2021-05-06 19:37:19.037 KubeController][0m Reconciling cluster dask-gateway.70c3ceb24dde4820a96a573f41002c4d
[32m[I 2021-05-06 19:37:19.037 KubeController][0m Finished reconciling cluster dask-gateway.70c3ceb24dde4820a96a573f41002c4d
[32m[I 2021-05-06 19:37:19.037 KubeController][0m Reconciling cluster dask-gateway.98cab07cde744758b6f43a1f3d19b837
[32m[I 2021-05-06 19:37:19.037 KubeController][0m Finished reconciling cluster dask-gateway.98cab07cde744758b6f43a1f3d19b837
[32m[I 2021-05-06 19:37:19.037 KubeController][0m Reconciling cluster dask-gateway.9f7fc2a6462c4cc39e2f724e1be8d429
[32m[I 2021-05-06 19:37:19.037 KubeController][0m Finished reconciling cluster dask-gateway.9f7fc2a6462c4cc39e2f724e1be8d429
[32m[I 2021-05-06 19:37:19.037 KubeController][0m Reconciling cluster dask-gateway.dc20587b3c4c492e94be734fea35b8a8
[32m[I 2021-05-06 19:37:19.037 KubeController][0m Finished reconciling cluster dask-gateway.dc20587b3c4c492e94be734fea35b8a8
[32m[I 2021-05-06 19:37:19.037 KubeController][0m Reconciling cluster dask-gateway.e3cfebb07aee4e4485518a5758029299
[32m[I 2021-05-06 19:37:19.038 KubeController][0m Finished reconciling cluster dask-gateway.e3cfebb07aee4e4485518a5758029299
[32m[I 2021-05-06 19:37:19.043 KubeController][0m dask-gateway-kube-controller started!
[32m[I 2021-05-06 19:37:19.043 KubeController][0m API listening at http://:8000
[32m[I 2021-05-06 19:38:02.208 KubeController][0m Reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:02.337 KubeController][0m Creating new credentials for cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:02.369 KubeController][0m Creating scheduler pod for cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:02.400 KubeController][0m Finished reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:02.402 KubeController][0m Reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:02.403 KubeController][0m Finished reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:03.466 KubeController][0m Reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:03.466 KubeController][0m Creating scheduler service for cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:03.489 KubeController][0m Finished reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:03.490 KubeController][0m Reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:03.490 KubeController][0m Finished reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:06.713 KubeController][0m Reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:06.713 KubeController][0m Finished reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:06.722 KubeController][0m Reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:06.722 KubeController][0m Creating scheduler HTTP route for cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:06.731 KubeController][0m Creating scheduler TCP route for cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:06.750 KubeController][0m Finished reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:06.751 KubeController][0m Reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:06.751 KubeController][0m Finished reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:07.588 KubeController][0m Reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:07.589 KubeController][0m Cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4 scaled to 1 - creating 1 workers, deleting 0 stopped workers
[32m[I 2021-05-06 19:38:07.609 KubeController][0m Finished reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:07.643 KubeController][0m Reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:07.643 KubeController][0m Finished reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:08.903 KubeController][0m Reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4
[32m[I 2021-05-06 19:38:08.903 KubeController][0m Finished reconciling cluster dask-gateway.7c570325fec840e69cdc5bd95c349bd4

```

**What happened**:     client = cluster.get_client() throws exception

**What you expected to happen**:     client = cluster.get_client() should work

**Environment**: AKS 1.20.5

- Dask version: 0.9.0 helm chart
- Python version: 3.8.5
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): pip

**Comment by jabbera** [comment]
Additional information: 

I created a public cluster and used the following values.yml and it still failed with the same error:

gateway:
  auth:
    type: simple
    simple:
      password: test

**Comment by jabbera** [comment]
Sorted via: pip install dask==2.30.0 dask-gateway==0.9.0 distributed==2.30.1

Any chance of getting a more modern version?

**Comment by totycro** [comment]
I'm still experiencing exactly the same issue with dask 2021.7.1. Is there another solution besides downgrading dask to 2.30.0?

**Comment by martindurant** [comment]
I believe we need to update the docker images, which we certainly plan to do that eventually.

**Comment by brews** [comment]
I've just bumped this issue after trying to prototype with recent dask and dask-gateway docker images.

Manually downgrading or `pip install dask==2.30.0 dask-gateway==0.9.0 distributed==2.30.1` remains the most reliable workaround I've found.
