### ISSUE TITLE
Quick start failing (localhost ClientConnectorError)

### ISSUE THREAD

**Issue by viciousCookie** [dask/dask-gateway#461]
**What happened**:

I've just followed quick start tutorial (https://gateway.dask.org/install-local.html), to try out gateway locally. Got the error bellow. Tried on two different machines with new conda environment created just for this test, same outcome.

```
Traceback (most recent call last):
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8789)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/site-packages/dask_gateway/client.py", line 455, in list_clusters
    return self.sync(self._clusters, status=status, **kwargs)
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/site-packages/dask_gateway/client.py", line 343, in sync
    return future.result()
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/site-packages/dask_gateway/client.py", line 434, in _clusters
    resp = await self._request("GET", url)
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/site-packages/dask_gateway/client.py", line 396, in _request
    resp = await session.request(method, url, json=json, **self._request_kwargs)
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/dana/.conda/envs/dask_dev/lib/python3.8/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:8789 ssl:default [Connect call failed ('127.0.0.1', 8789)]
```

**What you expected to happen**:

Expected to get blank list as in the tutorial.

**Minimal Complete Verifiable Example**:

```python
from dask_gateway import Gateway
gateway = Gateway("http://127.0.0.1:8789") # I've also tried other ports + firewall is down (if that matters)
gateway.list_clusters()
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.11.1 (dask-gateway 0.9.0)
- Python version: 3.8
- Operating System: Ubuntu 18.04.2 LTS
- Install method (conda, pip, source): conda

**Comment by viciousCookie** [comment]
wow..cant believe I've made that mistake, server was running in a script on a wrong port. Closing the issue.
