### ISSUE TITLE
ClientResponseError: 401, message='Unauthorized', url=URL('http://proxy-public/services/dask-gateway/api/v1/options')

### ISSUE THREAD

**Issue by thomafred** [dask/dask-gateway#566]
When trying to connect to the dask-gateway (deployed via helm-chart) from jupyterhub (deployed via zero-to-k8s helm chart), I am getting an `Unauthorized`-error

**What happened**:

When trying to get the cluster options, I get the following error:
```
ClientResponseError: 401, message='Unauthorized', url=URL('http://proxy-public/services/dask-gateway/api/v1/options')
```

**What you expected to happen**:

Gateway should return the cluster options

**Minimal Complete Verifiable Example**:

Code:

```python
from dask_gateway import Gateway

gateway = Gateway()
options = gateway.cluster_options()
```

Relevant dask-gateway helm-chart values:
```yaml
gateway:
  prefix: "/services/dask-gateway"
  auth:
    jupyterhub:
      apiToken: "${api_token}"
      apiUrl: http://proxy-public/hub/api
```

Relevant jupyterhub helm-chart values:
```yaml
hub:
  services:
    dask-gateway:
      apiToken: "${api_token}"
  extraConfig:
    # Register Dask Gateway service and setup singleuser environment.
    00-add-dask-gateway-values: |
      # 1. Sets `DASK_GATEWAY__PROXY_ADDRESS` in the singleuser environment.
      # 2. Adds the URL for the Dask Gateway JupyterHub service.
      import os
      # These are set by jupyterhub.
      if "PROXY_HTTP_SERVICE_HOST" in os.environ:
          # https is enabled, we want to use the internal http service.
          gateway_address = "http://{}:{}/services/dask-gateway/".format(
              os.environ["PROXY_HTTP_SERVICE_HOST"],
              os.environ["PROXY_HTTP_SERVICE_PORT"],
          )
          print("Setting DASK_GATEWAY__ADDRESS {} from HTTP service".format(gateway_address))
      else:
          gateway_address = "http://proxy-public/services/dask-gateway"
          print("Setting DASK_GATEWAY__ADDRESS {}".format(gateway_address))
      # Internal address to connect to the Dask Gateway.
      c.KubeSpawner.environment.setdefault("DASK_GATEWAY__ADDRESS", gateway_address)
      # Internal address for the Dask Gateway proxy.
      c.KubeSpawner.environment.setdefault("DASK_GATEWAY__PROXY_ADDRESS", "gateway://traefik-dask-gateway:80")
      # Relative address for the dashboard link.
      c.KubeSpawner.environment.setdefault("DASK_GATEWAY__PUBLIC_ADDRESS", "/services/dask-gateway/")
      # Use JupyterHub to authenticate with Dask Gateway.
      c.KubeSpawner.environment.setdefault("DASK_GATEWAY__AUTH__TYPE", "jupyterhub")
      # Adds Dask Gateway as a JupyterHub service to make the gateway available at
      # {HUB_URL}/services/dask-gateway
      service_url = "http://traefik-dask-gateway"
      for service in c.JupyterHub.services:
          if service["name"] == "dask-gateway":
              if not service.get("url", None):
                  print("Adding dask-gateway service URL")
                  service.setdefault("url", service_url)
              break
      else:
          print("dask-gateway service not found. Did you set jupyterhub.hub.services.dask-gateway.apiToken?")
    10-patch-dask-labextension-config: |-
      c.KubeSpawner.environment["DASK_GATEWAY__ADDRESS"] = "http://proxy-public/services/dask-gateway/"
      c.KubeSpawner.environment["DASK_GATEWAY__PUBLIC_ADDRESS"] = "https://${host}/services/dask-gateway/"
      c.KubeSpawner.environment.setdefault("DASK_LABEXTENSION__FACTORY__MODULE", "dask_gateway")
      c.KubeSpawner.environment.setdefault("DASK_LABEXTENSION__FACTORY__CLASS", "GatewayCluster")
      c.KubeSpawner.environment.setdefault("DASK_LABEXTENSION__FACTORY__ARGS", "[]")
      c.KubeSpawner.environment.setdefault("DASK_LABEXTENSION__FACTORY__KWARGS", "{}")
```

**Anything else we need to know?**:

Could this be related to

**Environment**:

- Dask version: 2022.05.0
- Dask gateway version: 2022.4.0
- JupyterHub version: 2.3.0
- Python version: 3.9.12
- Operating System: Linux/Pangeo-based image
- Install method (conda, pip, source): pip

**Comment by consideRatio** [comment]
- Since you configure dask-gateway via environment variables set dynamically, have you confirmed that they are set? Inspect `env` from a terminal.
- Are you deploying jupyterhub and dask-gateway in the same namespace? I think you are, but that is an implicit assumption in the configuration you have above.
- Have you observed this when using the dask-gateway 0.9.0 helm chart version as well, or is this your initial setup?
- Have you observed logs in the `api` pod about this 401 response? I want to ensure we conclude the 401 response comes from the `dask-gateway-server` software running in the `api` pod rather than the `proxy` pod or similar.

---

If you know this is a regression, its a big deal for my motivation to investigate it. I've not experienced these kinds of issues myself. I manage a deployment of a jupyterhub + dask-gateway, and it is configured [here](https://github.com/2i2c-org/infrastructure/blob/62bd7fe1755025d58681dee540381a7d1b64c125/helm-charts/daskhub/values.yaml#L155-L235) specifically to have certain options. You don't seem to have that, maybe that is required aso?

Please do your absolute best to investigate this further on your own. I think its too much work to help you investigate this in detail in order to rule out this isn't just some misconfiguration but actually is a reproducible bug based on reasonable configuration that should work.

**Comment by thomafred** [comment]
It seems the issue was that I had forgotten to set `gateway.auth.type=jupyterhub`.

However, I am now seeing some 502-errors:
```
ClientResponseError: 502, message='Bad Gateway', url=URL('http://proxy-public/services/dask-gateway/api/v1/options')
```

From the JupyterHub POD, it seems to be an issue with the scopes:
```
[E 2022-05-18 12:08:58.132 JupyterHub web:1789] Uncaught exception GET /hub/api/authorizations/token/[secret] (10.240.0.100)
    HTTPServerRequest(protocol='http', host='10.0.145.222:8081', method='GET', uri='/hub/api/authorizations/token/[secret]', version='HTTP/1.1', remote_ip='10.240.0.100')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1683, in _execute
        result = await result
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 98, in prepare
        self._resolve_roles_and_scopes()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 436, in _resolve_roles_and_scopes
        self.expanded_scopes = scopes.get_scopes_for(orm_token)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/scopes.py", line 349, in get_scopes_for
        expand_scopes(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/_memoize.py", line 95, in cached
        result = func(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/scopes.py", line 519, in expand_scopes
        expanded_scopes = set(chain.from_iterable(map(_expand_scope, scopes)))
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/scopes.py", line 459, in _expand_scope
        _add_subscopes(scope_name)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/scopes.py", line 455, in _add_subscopes
        if scope_definitions[scope_name].get('subscopes'):
    KeyError: 'all'

[E 2022-05-18 12:08:58.133 JupyterHub log:178] {
      "Host": "10.0.145.222:8081",
      "Authorization": "token [secret]",
      "Accept": "*/*",
      "Accept-Encoding": "gzip, deflate",
      "User-Agent": "Python/3.10 aiohttp/3.8.1"
    }
[E 2022-05-18 12:08:58.133 JupyterHub log:186] 500 GET /hub/api/authorizations/token/[secret] (dask-gateway@10.240.0.100) 18.59ms
```

**Comment by thomafred** [comment]
Also - sorry, forgot to answer your questions:

> Since you configure dask-gateway via environment variables set dynamically, have you confirmed that they are set? Inspect env from a terminal.

My bad, seems I forgot to set `gateway.auth.type`.

> Are you deploying jupyterhub and dask-gateway in the same namespace? I think you are, but that is an implicit assumption in the configuration you have above.

Yes, we are deploying these two services to the same namespace

> Have you observed this when using the dask-gateway 0.9.0 helm chart version as well, or is this your initial setup?

We were previously using the daskhub helm-chart. It does unfortunately not support Kubernetes v1.22+ as the gateway chart is outdated. This prompted us to start using the jupyterhub and dask-gateway charts directly. The old chart was using version `0.9.0` of the gateway, but we are now using `2022.4.0`.
 
> Have you observed logs in the api pod about this 401 response? I want to ensure we conclude the 401 response comes from the dask-gateway-server software running in the api pod rather than the proxy pod or similar.

We did indeed see the 401 errors in the API-pod, but it was likely due to the token missing as `gateway.auth.type` was using the default value of `simple` instead of `jupyterhub`.

**Comment by thomafred** [comment]
The `KeyError` was caused by the scope of some tokens being set to `all`, which does not exist ([ref](https://github.com/jupyterhub/jupyterhub/blob/main/jupyterhub/scopes.py#L33)). Truncating the token-table fixed this.

Next I got an error when attempting to validate the user token. Adding `"access:services"` to the scopes of the `user` role in the database (`roles`-table) fixed this, and I am finally able to get the cluster options. Creating and scaling clusters also works again.

The cluster options are controlled in a similar way by providing an options-handler as yourself (see code below).

Thank you so much for your help!

```python
from dask_gateway_server.options import Options, Integer, Float, String, Select, Mapping
import string


def escape(to_escape, safe, escape_char, allow_collisions=False):
    def _escape_char(c, escape_char):
        """Escape a single character"""
        buf = []
        for byte in c.encode('utf8'):
            buf.append(escape_char)
            buf.append('%X' % byte)
            return ''.join(buf)

    if isinstance(to_escape, bytes):
        # always work on text
        to_escape = to_escape.decode('utf8')

    if not isinstance(safe, set):
        safe = set(safe)

    if allow_collisions:
        safe.add(escape_char)
    elif escape_char in safe:
        warnings.warn(
            "Escape character %r cannot be a safe character."
            " Set allow_collisions=True if you want to allow ambiguous escaped strings."
            % escape_char,
            RuntimeWarning,
            stacklevel=2,
            )
        safe.remove(escape_char)

    chars = []
    for c in to_escape:
        if c in safe:
            chars.append(c)
        else:
            chars.append(_escape_char(c, escape_char))
    return u''.join(chars)

safe_chars = set(string.ascii_lowercase + string.digits)

default_profiles = {
    "minimal": {"worker_cores": 1, "worker_memory": 3, "cluster_max_workers": 2},
    "small": {"worker_cores": 2, "worker_memory": 6, "cluster_max_workers": 4},
    "medium": {"worker_cores": 4, "worker_memory": 12, "cluster_max_workers": 10},
}

def cluster_options(user):
    def options_handler(options):

        # Add labels and annotations specifying which user spawned the cluster
        extra_labels = {
            "hub.jupyter.org/username": escape(user.name, safe=safe_chars, escape_char="-")
        }
        extra_annotations = {
            "hub.jupyter.org/username": user.name
        }

        return {
            "worker_cores": 0.9 * options.worker_cores,
            "worker_cores_limit": options.worker_cores,
            "worker_memory": "%fG" % (0.88 * options.worker_memory),
            "worker_memory_limit": "%fG" % options.worker_memory,
            "cluster_max_workers": options.max_workers,
            "worker_extra_pod_annotations": extra_annotations,
            "worker_extra_pod_labels": extra_labels,
            "scheduler_extra_pod_labels": extra_labels,
            "scheduler_extra_pod_annotations": extra_annotations,
            "environment": options.environment,
        }

    if "${dask_large_profile_group}" in user.groups:
        # Large profile does not actually exist, instead we use medium as a placeholder
        base_profile = default_profiles["medium"]
    if "${dask_medium_profile_group}" in user.groups:
        base_profile = default_profiles["medium"]
    elif "${dask_small_profile_group}" in user.groups:
        base_profile = default_profiles["small"]
    else:
        base_profile = default_profiles["minimal"]

    default_env = {}
    return Options(
        Float("worker_cores", 1, min=0.1, max=base_profile["worker_cores"], label="Worker Cores"),
        Float("worker_memory", 2, min=1, max=base_profile["worker_memory"], label="Worker Memory (GiB)"),
        Integer("max_workers", 2, min=1, max=base_profile["cluster_max_workers"], label="Max worker count"),
        Mapping("environment", default=default_env, label="Environment Variables"),
        handler=options_handler,
    )

c.Backend.cluster_options = cluster_options
```

**Comment by consideRatio** [comment]
Thank you @thomafred for your followup and working to resolve this issue, and providing a record of what was wrong for others if they end up with the same symptoms!
