### ISSUE TITLE
Failure to build wheel since a few weeks back

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#632]
We now run into a failure on main branch that we didn't run into a few weeks ago.

```
running install_scripts
creating build/bdist.linux-x86_64/wheel/dask_gateway_server-2022.10.0.dist-info/WHEEL
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 249, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/tmp/build-env-xjtwyjcx/lib/python3.10/site-packages/setuptools/build_meta.py", line 412, in build_wheel
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',
  File "/tmp/build-env-xjtwyjcx/lib/python3.10/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
    self.run_setup()
  File "/tmp/build-env-xjtwyjcx/lib/python3.10/site-packages/setuptools/build_meta.py", line 483, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/tmp/build-env-xjtwyjcx/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 226, in <module>
  File "/tmp/build-env-xjtwyjcx/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/tmp/build-env-xjtwyjcx/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/tmp/build-env-xjtwyjcx/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/tmp/build-env-xjtwyjcx/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/tmp/build-env-xjtwyjcx/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/tmp/build-env-xjtwyjcx/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "<string>", line 84, in run
  File "/tmp/build-env-xjtwyjcx/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 385, in run
    with WheelFile(wheel_path, "w", self.compression) as wf:
  File "/tmp/build-env-xjtwyjcx/lib/python3.10/site-packages/wheel/wheelfile.py", line 45, in __init__
    raise WheelError(f"Bad wheel filename {basename!r}")
wheel.cli.WheelError: Bad wheel filename 'dask_gateway_server-2022.10.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'
```

The difference is build was updated from `0.8.0` to `0.9.0`.

Actually, a new release of `wheel` is the cause, and specifically https://github.com/pypa/wheel/commit/88f02bc335d5404991e532e7f3b0fc80437bf4e0.

**Comment by consideRatio** [comment]
It comes down to the `.` in `manylinux_2_17_x86_64.manylinux2014_x86_64` not being allowed.
