### ISSUE TITLE
SQLAlchemy default installs v2.0, dask-gateway-server uses 1.4.x syntax

### ISSUE THREAD

**Issue by klucar** [dask/dask-gateway#715]
**Describe the issue**:

dask-gateway-server is using SQLAlchemy db.execute call which is 1.4.x syntax. SQLAlchemy v2.0.0 was released on January 26, 2023 and is now the default when not specifying a version number using pip.

Probably the case with conda too, but I didn't check

**Minimal Complete Verifiable Example**:

```bash
$ python3 -m venv venv
$ source venv/bin/activate
(venv) dask@xxxx:~ pip install dask-gateway dask-gateway-server[local]   

(venv) dask@xxxx:~$ dask-gateway-server
[I 2023-06-05 06:55:05.889 DaskGateway] Starting dask-gateway-server - version 2023.1.1
[I 2023-06-05 06:55:05.890 DaskGateway] Authenticator: 'dask_gateway_server.auth.SimpleAuthenticator'                                                                               [I 2023-06-05 06:55:06.018 DaskGateway] Backend: 'dask_gateway_server.backends.local.UnsafeLocalBackend'                                                                            [I 2023-06-05 06:55:06.021 DaskGateway] Generating new api token for proxy
[I 2023-06-05 06:55:06.021 DaskGateway] Starting the Dask gateway proxy...
[I 2023-06-05 06:55:06.080 DaskGateway] Dask gateway proxy started
[I 2023-06-05 06:55:06.081 DaskGateway] - HTTP routes listening at http://:8000
[I 2023-06-05 06:55:06.081 DaskGateway] - Scheduler routes listening at gateway://:8000
[W 2023-06-05 06:55:06.083 Proxy] Unexpected failure fetching routing table, retrying in 0.5s: Get "http://127.0.0.1:35087/api/v1/routes": dial tcp 127.0.0.1:35087: connect: connection refused
[C 2023-06-05 06:55:06.089 DaskGateway] Failed to start gateway, shutting down
Traceback (most recent call last):
  File "/home/dask/venv/lib/python3.10/site-packages/dask_gateway_server/app.py", line 243, in main                                                                                     await self.setup()
  File "/home/dask/venv/lib/python3.10/site-packages/dask_gateway_server/app.py", line 198, in setup                                                                                    await self.backend.setup(self.app)
  File "/home/dask/venv/lib/python3.10/site-packages/dask_gateway_server/backends/db_base.py", line 835, in setup                                                                       self.db = DataManager(
  File "/home/dask/venv/lib/python3.10/site-packages/dask_gateway_server/backends/db_base.py", line 835, in setup                                                          [123/334]
    self.db = DataManager(
  File "/home/dask/venv/lib/python3.10/site-packages/dask_gateway_server/backends/db_base.py", line 337, in __init__                                                                    for c in self.db.execute(clusters.select()):
AttributeError: 'Engine' object has no attribute 'execute'
```

**Anything else we need to know?**:

Problem was fixed by doing:
pip install SQLAlchemy==1.4.48

**Environment**:

- Dask version:  2023.5.1
- Python version: 3.10.6
- Operating System: Ubuntu 22.04.2 LTS
- Install method (conda, pip, source): pip

**Comment by consideRatio** [comment]
I think this has been patched in https://github.com/dask/dask-gateway/pull/685, but we haven't made a release.

Right now, tests are failing and I can't get why, so I'm cautious to making a release with failing tests - see #709.

**Comment by klucar** [comment]
I see. That's a pain to figure out. We recently went to using pip-compile to pin transitive dependencies.
